# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
  
cache:
    pip: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install coveralls
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script: coverage run --source pymaybe setup.py test

after_success: coveralls

